# Generated by Django 5.2.4 on 2025-07-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Body type',
                'verbose_name_plural': 'Body types',
                'db_table': 'body_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Drive type',
                'verbose_name_plural': 'Drive types',
                'db_table': 'drive_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Engine type',
                'verbose_name_plural': 'Engine types',
                'db_table': 'engine_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Transmission type',
                'verbose_name_plural': 'Transmission types',
                'db_table': 'transmission_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vin_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3)),
                ('horsepower', models.IntegerField()),
                ('production_year', models.IntegerField(verbose_name='Год выпуска')),
                ('mileage', models.IntegerField()),
                ('is_credit', models.BooleanField(default=False)),
                ('credit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_exchange', models.BooleanField(default=False)),
                ('exchange_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='car_img/')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodytype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.color')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drivetype')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enginetype')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transmissiontype')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'car',
                'ordering': ['-id'],
            },
        ),
    ]
