# Generated by Django 5.2.4 on 2025-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bodytype_drivetype_enginetype_transmissiontype_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
